name: wfc3_env
channels:
- astropy
- http://ssb.stsci.edu/astroconda
- defaults
dependencies:
- astropy-healpix=0.5=py37h8ba3199_1
- astroquery=0.4.1=pyh9f0ad1d_0
- astroscrappy=1.0.8=py37h37391d0_1003
- ccdproc=2.1.0=py_0
- python_abi=3.7=1_cp37m
- reproject=0.7.1=py37h8ba3199_1
- alabaster=0.7.12=py_0
- appnope=0.1.0=py37_0
- asn1crypto=1.2.0=py37_0
- astropy=4.0=py37h1de35cc_0
- attrs=19.3.0=py_0
- babel=2.7.0=py_0
- backcall=0.1.0=py37_0
- beautifulsoup4=4.8.1=py37_0
- blas=1.0=mkl
- bleach=3.1.0=py_0
- bokeh=1.4.0=py37_0
- bottleneck=1.3.1=py37h1d22016_0
- ca-certificates=2019.11.27=0
- certifi=2019.11.28=py37_0
- cffi=1.13.2=py37hb5b8e2f_0
- chardet=3.0.4=py37_1003
- click=7.0=py_0
- cloudpickle=1.2.2=py_0
- cryptography=2.8=py37ha12b0ac_0
- cycler=0.10.0=py37_0
- cython=0.29.14=py37h0a44026_0
- cytoolz=0.10.1=py37h1de35cc_0
- d2to1=0.2.12.post1=pyh91ea838_0
- dask=2.9.0=py_0
- dask-core=2.9.0=py_0
- dbus=1.13.12=h90a0687_0
- decorator=4.4.1=py_0
- defusedxml=0.6.0=py_0
- dill=0.3.1.1=py37_0
- distributed=2.9.0=py_0
- docutils=0.15.2=py37_0
- entrypoints=0.3=py37_0
- et_xmlfile=1.0.1=py37_0
- expat=2.2.6=h0a44026_0
- fast-histogram=0.7=py37h1d22016_1000
- filelock=3.0.12=py_0
- freetype=2.9.1=hb4e5f40_0
- fsspec=0.6.2=py_0
- gettext=0.19.8.1=h15daf44_3
- glib=2.63.1=hd977a24_0
- glue-core=0.15.6=py37_0
- h5py=2.9.0=py37h3134771_0
- hdf5=1.10.4=hfa1e0ec_0
- heapdict=1.0.1=py_0
- html5lib=1.0.1=py_0
- hypothesis=4.54.2=py37_0
- icu=58.2=h4b95b61_1
- idna=2.8=py37_0
- imageio=2.6.1=py37_0
- imagesize=1.1.0=py_0
- importlib_metadata=1.3.0=py37_0
- intel-openmp=2019.4=233
- ipykernel=5.1.3=py37h39e3cac_0
- ipython=7.11.1=py37h39e3cac_0
- ipython_genutils=0.2.0=py37_0
- ipywidgets=7.5.1=py_0
- jdcal=1.4.1=py_0
- jedi=0.15.1=py37_0
- jinja2=2.10.3=py_0
- joblib=0.14.1=py_0
- jpeg=9b=he5867d9_2
- jsonschema=3.2.0=py37_0
- jupyter_client=5.3.4=py37_0
- jupyter_core=4.6.1=py37_0
- keyring=20.0.0=py37_0
- kiwisolver=1.1.0=py37h0a44026_0
- libcxx=4.0.1=hcfea43d_1
- libcxxabi=4.0.1=hcfea43d_1
- libedit=3.1.20181209=hb402a30_0
- libffi=3.2.1=h475c297_4
- libgcc=4.8.5=hdbeacc1_10
- libgfortran=3.0.1=h93005f0_2
- libiconv=1.15=hdd342a3_7
- libpng=1.6.37=ha441bb4_0
- libsodium=1.0.16=h3efe00b_0
- libtiff=4.1.0=hcb84e12_0
- libxml2=2.9.9=hf6e021a_1
- libxslt=1.1.33=h33a18ac_0
- llvm-openmp=4.0.1=hcfea43d_1
- locket=0.2.0=py37_1
- lockfile=0.12.2=py37_0
- lxml=4.4.2=py37hef8c89e_0
- markupsafe=1.1.1=py37h1de35cc_0
- matplotlib=3.1.1=py37h54f8f79_0
- mistune=0.8.4=py37h1de35cc_0
- mkl=2019.4=233
- mkl-service=2.3.0=py37hfbe908c_0
- mkl_fft=1.0.15=py37h5e564d8_0
- mkl_random=1.1.0=py37ha771720_0
- mock=3.0.5=py37_0
- more-itertools=8.0.2=py_0
- mpl-scatter-density=0.6=py_0
- msgpack-python=0.6.1=py37h04f5b5a_1
- nbconvert=5.6.1=py37_0
- nbformat=4.4.0=py37_0
- ncurses=6.1=h0a44026_1
- networkx=2.4=py_0
- nose=1.3.7=py37_2
- notebook=6.0.2=py37_0
- numpy=1.17.4=py37h890c691_0
- numpy-base=1.17.4=py37h6575580_0
- numpydoc=0.9.1=py_0
- olefile=0.46=py_0
- openpyxl=3.0.2=py_0
- openssl=1.1.1d=h1de35cc_3
- packaging=19.2=py_0
- pandas=0.25.3=py37h0a44026_0
- pandoc=2.2.3.2=0
- pandocfilters=1.4.2=py37_1
- parso=0.5.2=py_0
- partd=1.1.0=py_0
- pcre=8.43=h0a44026_0
- pexpect=4.7.0=py37_0
- pickleshare=0.7.5=py37_0
- pillow=6.2.1=py37hb68e598_0
- pip=19.3.1=py37_0
- pkg-config=0.29.2=h3efe00b_8
- pkgconfig=1.4.0=py37_0
- plotly=4.4.1=py_0
- pluggy=0.13.1=py37_0
- prometheus_client=0.7.1=py_0
- prompt_toolkit=3.0.2=py_0
- psutil=5.6.7=py37h1de35cc_0
- ptyprocess=0.6.0=py37_0
- py=1.8.0=py_0
- pycparser=2.19=py_0
- pygments=2.5.2=py_0
- pyopenssl=19.1.0=py37_0
- pyparsing=2.4.5=py_0
- pyqt=5.9.2=py37h655552a_2
- pyqtgraph=0.10.0=pyh91ea838_3
- pyrsistent=0.15.6=py37h1de35cc_0
- pysocks=1.7.1=py37_0
- pytest=5.3.2=py37_0
- pytest-arraydiff=0.3=py37h39e3cac_0
- pytest-astropy=0.7.0=py_0
- pytest-astropy-header=0.1.1=py_0
- pytest-doctestplus=0.5.0=py_0
- pytest-openfiles=0.4.0=py_0
- pytest-remotedata=0.3.2=py37_0
- python=3.7.5=h359304d_0
- python-dateutil=2.8.1=py_0
- python.app=2=py37_9
- pytz=2019.3=py_0
- pywavelets=1.0.3=py37h1d22016_1
- pyyaml=5.2=py37h1de35cc_0
- pyzmq=18.1.0=py37h0a44026_0
- qt=5.9.7=h468cd18_1
- qtawesome=0.6.0=py_0
- qtconsole=4.6.0=py_0
- qtpy=1.9.0=py_0
- readline=7.0=h1de35cc_5
- requests=2.22.0=py37_1
- retrying=1.3.3=py_2
- scikit-image=0.15.0=py37h0a44026_0
- scikit-learn=0.21.3=py37h27c97d8_0
- scipy=1.3.1=py37h1410ff5_0
- send2trash=1.5.0=py37_0
- setuptools=44.0.0=py37_0
- setuptools_scm=3.3.3=py_0
- sip=4.19.8=py37h0a44026_0
- six=1.13.0=py37_0
- snowballstemmer=2.0.0=py_0
- sortedcontainers=2.1.0=py37_0
- soupsieve=1.9.5=py37_0
- sphinx=2.3.0=py_0
- sphinxcontrib-applehelp=1.0.1=py_0
- sphinxcontrib-devhelp=1.0.1=py_0
- sphinxcontrib-htmlhelp=1.0.2=py_0
- sphinxcontrib-jsmath=1.0.1=py_0
- sphinxcontrib-qthelp=1.0.2=py_0
- sphinxcontrib-serializinghtml=1.1.3=py_0
- sqlite=3.30.1=ha441bb4_0
- tblib=1.6.0=py_0
- terminado=0.8.3=py37_0
- testpath=0.4.4=py_0
- tk=8.6.8=ha441bb4_0
- toolz=0.10.0=py_0
- tornado=6.0.3=py37h1de35cc_0
- traitlets=4.3.3=py37_0
- urllib3=1.25.7=py37_0
- wcwidth=0.1.7=py37_0
- webencodings=0.5.1=py37_1
- wheel=0.33.6=py37_0
- widgetsnbextension=3.5.1=py37_0
- xlrd=1.2.0=py_0
- xz=5.2.4=h1de35cc_4
- yaml=0.1.7=hc338f04_2
- zeromq=4.3.1=h0a44026_3
- zict=1.0.0=py_0
- zipp=0.6.0=py_0
- zlib=1.2.11=h1de35cc_3
- zstd=1.3.7=h5bba6e5_0
- acstools=3.0.0=py37_0
- asdf=2.4.2=py37_0
- asteval=0.9.13=py37_0
- astroimtools=0.2=py37_0
- calcos=3.3.7=py37_0
- cfitsio=3.440=1
- costools=1.2.3=py37_0
- crds=7.4.1.3=py37_0
- da5-notebooks=1.0=1
- drizzlepac=3.1.3=py37_0
- ds9=8.0.1=0
- fftw=3.3.4=1
- fitsblender=0.3.6=py37_0
- fitsverify=4.18=6
- ginga=3.0.1=py37_0
- gwcs=0.11.0=py37_0
- hstcal=2.3.1=0
- htc_utils=0.1.0=py37_1
- imexam=0.8.1=py37_0
- jwxml=0.3.0=py37_1
- mosviz=0.3.0=py37_0
- nictools=1.1.5=py37_0
- parsley=1.3=py37_1
- photutils=0.7.2=py37_0
- poppy=0.9.0=py37_0
- pyds9=1.9.0.dev145+gc1bf67a=py37_2
- pyfftw=0.9.2=py37_3
- pysiaf=0.6.3=py37_0
- pysynphot=0.9.14=py37_0
- reftools=1.7.5=py37_0
- semantic_version=2.6.0=py37_0
- specutils=0.6=py37_0
- specviz=0.7.0=py37_0
- spherical-geometry=1.2.18=py37_0
- stginga=1.0=py37_0
- stistools=1.3.0=py37_0
- stregion=1.1.6=py37_0
- stsci=3.2.0=py37_0
- stsci-data-analysis=3.0.0=py37_0
- stsci-hst=3.1.1=py37_0
- stsci.convolve=2.2.2=py37_1
- stsci.distutils=0.3.8=py37_2
- stsci.image=2.3.3=py37_0
- stsci.imagemanip=1.1.4=py37_1
- stsci.imagestats=1.6.2=py37_0
- stsci.ndimage=0.10.1=py37_3
- stsci.skypac=1.0.4=py37_0
- stsci.stimage=0.2.4=py37_0
- stsci.tools=3.6.0=py37_0
- stsynphot=1.0.0=py37_0
- stwcs=1.5.3=py37_0
- synphot=1.0.1=py37_0
- tweakwcs=0.5.3=py37_0
- webbpsf=0.9.0=py37_1
- webbpsf-data=0.9.0=1
- wfc3tools=1.3.5=py37_0
- wfpc2tools=1.0.4=py37_0

