name: Manual HTML Deploy

on:
  workflow_dispatch:

jobs:
  GenerateHTML:
   uses: spacetelescope/notebook-ci-actions/.github/workflows/ci_builder_manual_jdat.yml@v3
   with:
      python-version: ${{ vars.PYTHON_VERSION }}
