name: Manual HTML Deploy

on:
  workflow_dispatch:

jobs:
  GenerateHTML:
   uses: spacetelescope/notebook-ci-actions/.github/workflows/ci_builder_manual_jdat.yml@0ea14fcf22bfa36f86d7a9500003bf6454e6f2e5  # main
   with:
      python-version: ${{ vars.PYTHON_VERSION }}
