name: Deploy Nightly
on:
  schedule:
    - cron: '0 3 * * *' # run at 2 AM UTC

env:
  ARCH_ON_CI: "normal"
  IS_CRON: "true"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
    - name: Clear up disc space for nightly
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.12
      uses: actions/setup-python@v2 ## needed for caching
      with:
        python-version: 3.8.12
        cache: 'pip'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        #conda env update --file CIenvironment.yml --name base
        pip install -r requirements.txt
        pip install pytest
        pip install nbval
        pip install nbconvert
    - name: Execute notebooks
      run: |
        find . -name '*.ipynb' -type f -execdir jupyter nbconvert --template classic --to html --execute {} \; 
    - name: Test with pytest
      run: |
        pytest --nbval
