name: Manual Security Scan
on:
  workflow_dispatch:
  #schedule:
    #- cron: '0 3 * * *' # run at 2 AM UTC
   # - cron: '0 0 * * 0' # midnight sunday UTC

jobs:
  Scheduled:
   uses: spacetelescope/notebook-ci-actions/.github/workflows/ci_security_scan.yml@v3
