## This workflow scans all Jupyter notebooks in the repository for Section 508 accessibility issues.
## It is scheduled to run weekly on Sundays at 0100 UTC, but can also be triggered manually.
name: Weekly Jupyter Notebook Accessibility Check

on:
  # Weekly runs at 0100 UTC every Sunday
  schedule:
    - cron: "0 1 * * SUN"
  workflow_dispatch:

jobs:
    nb_a11y_check:
      uses: spacetelescope/notebook-ci-actions/.github/workflows/notebook_accessibility_check.yml@v1
