## This workflow performs PEP8 style checks on python scripts
name: PEP8 Script Style Check Execution

on:
   pull_request:
    branches:
      - main
    paths:
      - 'notebooks/**.py'
      - '*.yml'

jobs:
  Script_PEP8_Check:
   uses: spacetelescope/notebook-ci-actions/.github/workflows/script_pep8check.yml@v3
   with:
     python-version: ${{ vars.PYTHON_VERSION || '3.11' }}
