## This workflow performs PEP8 style checks on the python code in notebook code cells.
name: PEP8 Notebook Style Check Execution

on:
   pull_request:
    branches:
      - main
    paths:
      - 'notebooks/**.ipynb'
      - '*.yml'

jobs:
  Notebook_PEP8_Check:
   uses: spacetelescope/notebook-ci-actions/.github/workflows/notebook_pep8check.yml@v3
   with:
     python-version: ${{ vars.PYTHON_VERSION || '3.11'}}
