name: Weekly HTML Accessibility Check
on:
  schedule:
    - cron: '0 5 * * 0' # 0500 UTC every Sunday
  workflow_dispatch:
    inputs:
      total_error_limit:
        required: false
        description: 'The maximum total allowed number of HTML accessibility errors. To skip this testing requirement, enter the value "-1". If not explicitly specified, the default value is "0".'
        default: 0
        type: string
      total_warning_limit:
        required: false
        description: 'The maximum total allowed number of HTML accessibility warnings. To skip this testing requirement, enter the value "-1". If not explicitly specified, the default value is "0".'
        default: 0
        type: string

jobs:
  Scheduled:
   uses: spacetelescope/notebook-ci-actions/.github/workflows/html_accessibility_check.yml@v3
   with:
     target_url: https://spacetelescope.github.io/${{ github.event.repository.name }}/
     python-version: ${{ vars.PYTHON_VERSION }}
     total_error_limit: ${{ inputs.total_error_limit || 0 }}
     total_warning_limit: ${{ inputs.total_warning_limit || 0 }}
     
   secrets:
     A11YWATCH_TOKEN: ${{ secrets.A11YWATCH_TOKEN }}
