name: Weekly broken link check
on:
  schedule:
    - cron: '0 4 * * 0' # 0400 UTC every Sunday

jobs:
  Scheduled:
   uses: spacetelescope/notebook-ci-actions/.github/workflows/broken_link_checker.yml@0ea14fcf22bfa36f86d7a9500003bf6454e6f2e5  # main
   with:
     website_url: "https://spacetelescope.github.io/jdat_notebooks/"
